### PERSISTANCE VOLUME
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userservice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
### SERVICE RESOURCE
apiVersion: v1
kind: Service
metadata:
  name: userservice-db-svc
spec:
  selector:
    app: userservice-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
### USER-SERVICE DB DEPLOYMENT RESOURCE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-mongo
spec:
  selector:
    matchLabels:
      app: userservice-mongo
  template:
    metadata:
      labels:
        app: userservice-mongo
    spec:
      containers:
        - name: userservice-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: userdb-storage
              mountPath: /data
      volumes:
        - name: userdb-storage
          persistentVolumeClaim:
            claimName: userservice-pvc