## USER SERVICE - SERVICE RESOURCE
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 3001
  type: LoadBalancer ## EXPOSE FOR USAGE OUTSIDE CLUSTER NW
---
## USER SERVICE - DEPLOY RESOURCE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: audittoolusersvc.azurecr.io/user-service:1.0
          ports:
            - containerPort: 3001
          env:
            - name: USER_SERVICE_PORT
              value: "3001"
            - name: USER_DB_SERVICE
              value: "mongodb://userservice-db-svc:27017/user-db"
          imagePullPolicy: Always
